### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by elhadesgamer97** [kangarko/Protect#12]
Hello, I bought the protection plugin but when I started, I got that error and it didn't load, an error about downloading a file, etc., but according to the plugin it didn't need dependencies, how can I activate it or fix this problem?

[23:01:42 ERROR]: Protect 1.1.9 encountered a FileNotFoundException! Please check your error.log and report this issue with the information in that file. Running Paper 1.21-R0.1-SNAPSHOT and Java 21.0.3
[23:01:42 INFO]: java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/alessiodp/libby/maven/resolver/libby-maven-resolver/1.0.1/libby-maven-resolver-1.0.1.jar
[23:01:42 INFO]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1994)
[23:01:42 INFO]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[23:01:42 INFO]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[23:01:42 INFO]:        at Protect-1.1.9.jar//org.mineacademy.protect.lib.library.LibraryManager.downloadLibrary(LibraryManager.java:380)
[23:01:42 INFO]:        at Protect-1.1.9.jar//org.mineacademy.protect.lib.library.LibraryManager.downloadLibrary(LibraryManager.java:479)
[23:01:42 INFO]:        at Protect-1.1.9.jar//org.mineacademy.protect.lib.library.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:70)
[23:01:42 INFO]:        at Protect-1.1.9.jar//org.mineacademy.protect.lib.library.LibraryManager.resolveTransitiveLibraries(LibraryManager.java:587)
[23:01:42 INFO]:        at Protect-1.1.9.jar//org.mineacademy.protect.lib.library.LibraryManager.loadLibrary(LibraryManager.java:608)
[23:01:42 INFO]:        at Protect-1.1.9.jar//org.mineacademy.protect.lib.plugin.SimplePlugin.loadLibrary(SimplePlugin.java:1107)
[23:01:42 INFO]:        at Protect-1.1.9.jar//org.mineacademy.protect.lib.plugin.SimplePlugin.onLoad(SimplePlugin.java:235)
[23:01:42 INFO]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[23:01:42 INFO]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[23:01:42 INFO]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[23:01:42 INFO]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)

**Comment by kangarko** [comment]
Thanks, will be addressed.

**Comment by elhadesgamer97** [comment]
I have a question, how do I disable deleting items that have lore or RGB names? I set it and it instantly deleted the players' items, it practically screwed everything up for me. Is there a way to only avoid glitches or dupes and not delete custom-created items with lores, RGB names, their food stacks, golden apples?
