### ISSUE TITLE
Running Paper 1.20.6-R0.1-SNAPSHOT and Java 21.0.2

### ISSUE THREAD

**Issue by czHeso** [kangarko/Protect#14]
1) Put your Minecraft version in the title.
Running Paper 1.20.6-R0.1-SNAPSHOT and Java 21.0.2

2) Provide steps to reproduce your problem.
Start server

Plugin dont load on version v2.0.0 - when i downgrade version to v1.2.0, its works normally.
Anyway, there is error.log

------------------------------------[ 22.09.2024 06:18:42 ]-----------------------------------
Protect 2.0.0 encountered FoException
Running Paper 1.20.6-R0.1-SNAPSHOT and Java 21.0.2
Plugins: ViaVersion - 5.0.4-SNAPSHOT, LuckPerms - 5.4.134, Vault - 1.7.3-b131, FastAsyncWorldEdit - 2.10.1-SNAPSHOT-818;06bf710, WorldGuard - 7.0.10+d9424b1, PlaceholderAPI - 2.11.6, ProtocolLib - 5.3.0-SNAPSHOT-726, MythicMobs - 5.7.1-${CI_COMMIT_SHORT_SHA}, BKCommonLib - 1.20.6-v1, BentoBox - 2.4.1, HeadDatabase - 4.19.8, My_Worlds - 1.20.6-v1, CMILib - 1.5.0.9, DecentHolograms - 2.8.9, CoreProtect - 22.4, CMI - 9.7.4.7, ViaBackwards - 5.0.4-SNAPSHOT, SCore - 5.24.6.24, Residence - 5.1.5.3, GSit - 1.9.5, floodgate - 2.2.3-SNAPSHOT (b109-49bd564), LoneLibs - 1.0.56, ModelEngine - R4.0.7, ExecutableItems - 7.24.6.24, Skript - 2.8.2, Vulcan - 2.8.9, ItemsAdder - 4.0.2-alpha-test-3, Jobs - 5.2.3.1, ChestShop - 3.12.2 (build 353), AdvancedEnchantments - 9.9.5, zMenu - 1.0.3.2, nightcore - 2.6.2, VotingPlugin - 6.17, Brewery - 3.1.1, zAuctionHouseV3 - 3.2.1.9, ExcellentCrates - 5.2.3.1, ShopGUIPlus - 1.97.1, ChestSort - 14.1.0, SkinsRestorer - 15.2.0, DiscordSRV - 1.27.0, Vehicles - 14.7, NxChangelog - 1.0-SNAPSHOT, SocialNetworks - 1.8.3, BattlePass - 4.5.8, ArmorStandTools - 4.4.6, EasyWhitelist - 1.0.2, CMIEInjector - 1.0.2.4, TAB - 4.1.6, DeluxeTags - 1.8.2-Release, FastClearLag - 1.6.1, WebRewards - 9.0, BankPlus - 6.3-Alpha4, AxGens - 2.17.2, CommandPanels - 3.21.3.2, AutoMessages - 8.0, InventoryRollbackPlus - 1.6.17, FreeCoinFlip - 1.9, HostifyMonitor - 1.12, BungeeGuard - 1.3-SNAPSHOT, StoreStats - 3.39.3, Protect - 2.0.0, TradeMe - 6.2.1.5, ConsoleSpamFix - 1.10.0, ChatPingPlus - 1.1, InteractiveChat - 4.2.9.0, VoidGen - 2.2.1, ItemEdit - 3.4.2, FireMysteryBlocks - 2.3.13, spark - 1.10.71, KeepChunks - 1.7.2, CustomsMessagePlus - 2.6.1 - SNAPSHOT, PlugManX - 2.4.1, Plan - 5.6 build 2883, EnfAfkZone - 2.7, PlayerWarps - 3.0.0-BETA17, EasyCommandBlocker - 1.1, TrashCan - 1.0-SNAPSHOT, AdvancedPets - 2.9.19, DeluxeMenus - 1.14.0-Release, PreventPortBypass - 1.0, ChatItem - 2.6, QuickTax - 1.8.0, UltimateAutoRestart - 2024.06-a, BentoBox-Bank - 1.7.1, BentoBox-Likes - 2.4.0, BentoBox-Visit - 1.6.0, BentoBox-Warps - 1.14.0, BentoBox-CheckMeOut - 1.1.1, BentoBox-Biomes - 2.1.1, BentoBox-Limits - 1.22.0, BentoBox-Boxed - 2.6.1
----------------------------------------------------------------------------------------------

More Information: 
Internal path with JSON file at 'lang/en_US.json' does not exist!
FoException Report: Internal path with JSON file at 'lang/en_US.json' does not exist!
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.settings.Lang.readJsonFromInternal(Lang.java:161)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.settings.Lang.downloadLocale(Lang.java:138)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.settings.Lang.downloadLocales(Lang.java:88)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:236)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:96)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:357)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	 at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575)
----------------------------------------------------------------------------------------------

**Comment by czHeso** [comment]
@kangarko 
Stejný problém vlastně hlášený nyní i v https://github.com/kangarko/Protect/issues/15

Internal path with JSON file at 'lang/en_US.json' does not exist!
