### ISSUE TITLE
Error: FileNotFoundException

### ISSUE THREAD

**Issue by Philipp1497222007** [kangarko/Protect#15]
Plugin dosent work at all pls provide a fix . 
[error.log](https://github.com/user-attachments/files/17090205/error.log)

LOG: 
More Information: 
Unable to download locale en_US
FileNotFoundException https://raw.githubusercontent.com/kangarko/Foundation/refs/heads/v7/foundation-core/src/main/resources/overlay/lang/en_US.json?token=1727017609047
	 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2010)
	 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1615)
	 at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.FileUtil.readLinesFromUrl(FileUtil.java:181)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.settings.Lang.readJsonFromUrl(Lang.java:149)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.settings.Lang.downloadLocale(Lang.java:122)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.settings.Lang.downloadLocales(Lang.java:88)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:236)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:96)
	 at Protect-2.0.0.jar//org.mineacademy.protect.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:357)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	 at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Thanks, I apology for the error! Should be fixed now in the next release.
