### ISSUE TITLE
Error loading plugin. Minecraft Server Version: 1.21.1

### ISSUE THREAD

**Issue by vayner25** [kangarko/Protect#18]
[04:03:34 INFO]: [Protect] Enabling Protect v2.2.1
[04:03:34 INFO]: [Protect]  ___   ___   ___  _____  ____  __   _____
[04:03:34 INFO]: [Protect] | |_) | |_) / / \  | |  | |_  / /`   | |
[04:03:34 INFO]: [Protect] |_|   |_| \ \_\_/  |_|  |_|__ \_\_,  |_|
[04:03:34 INFO]:
[04:03:34 INFO]: org.mineacademy.protect.lib.exception.ReflectionException: Could not invoke public static litebans.api.Database litebans.api.Database.get() with params []
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:359)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:341)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.model.LiteBansHook.<init>(HookManager.java:3804)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.model.HookManager.loadDependencies(HookManager.java:224)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.platform.SimplePlugin.onEnable(SimplePlugin.java:405)
[04:03:34 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[04:03:34 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[04:03:34 INFO]: litebans.api.exception.MissingImplementationException: LiteBans API implementation is not available! This means that LiteBans is not installed on this server or it hasn't been loaded yet.
[04:03:34 INFO]:        at LiteBans.jar//litebans.api.Database.get(Database.java:27)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:356)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:341)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.model.LiteBansHook.<init>(HookManager.java:3804)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.model.HookManager.loadDependencies(HookManager.java:224)
[04:03:34 INFO]:        at Protect-2.2.1.jar//org.mineacademy.protect.lib.platform.SimplePlugin.onEnable(SimplePlugin.java:405)
[04:03:34 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[04:03:34 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[04:03:34 INFO]: [Protect]     ___                  _
[04:03:34 INFO]: [Protect]    / _ \  ___  _ __  ___| |
[04:03:34 INFO]: [Protect]   | | | |/ _ \| '_ \/ __| |
[04:03:34 INFO]: [Protect]   | |_| | (_) | |_) \__ \_|
[04:03:34 INFO]: [Protect]    \___/ \___/| .__/|___(_)
[04:03:34 INFO]: [Protect]              |_|
[04:03:34 INFO]: [Protect] !-----------------------------------------------------!
[04:03:34 INFO]: [Protect]  Error loading Protect v2.2.1, plugin is disabled!
[04:03:34 INFO]: [Protect]  Running on Paper 1.21.1-R0.1-SNAPSHOT & Java 22.0.1
[04:03:34 INFO]: [Protect] !-----------------------------------------------------!
[04:03:34 INFO]: [Protect]  Error: LiteBans API implementation is not available! This means that LiteBans is not installed on this server or it hasn't been loaded yet.
[04:03:34 INFO]: [Protect] !-----------------------------------------------------!
[04:03:34 INFO]: [Protect] Disabling Protect v2.2.1
[04:03:34 INFO]: [LiteBans] Enabling LiteBans v2.16.1
[04:03:34 INFO]: [LiteBans] Using default database drivers (version:8).
[04:03:34 INFO]: [LiteBans] Using system locale (ru)
[04:03:34 INFO]: [LiteBans] Loaded 2 templates from templates.yml!
[04:03:34 INFO]: [LiteBans] Loading SQL driver: mysql 8.0.29 (com.mysql.cj.jdbc.Driver)
[04:03:34 INFO]: [LiteBans] Connecting to database...
[04:03:34 INFO]: [LiteBans] Connected to MySQL database successfully (98,9 ms).
[04:03:34 INFO]: [LiteBans] Upgrading database tables...
[04:03:34 INFO]: [LiteBans] Upgrade complete.
[04:03:34 INFO]: [LiteBans] Database connection fully initialized (209 ms).
[04:03:34 INFO]: [LiteBans] v2.16.1 enabled. Startup took 359 ms.

**Comment by kangarko** [comment]
Can you try this quick trick > open Protect.jar > open plugin.yml inside the jar and add LiteBans to softdepend key? Save the edited jar while the server is stopped and restart. Thanks.
