### ISSUE TITLE
1.21: Strange error in the console

### ISSUE THREAD

**Issue by eugenio53390** [kangarko/Protect#6]
The error that is in the console is the following:

```
[00:31:12 ERROR]: Protect 1.1.5 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Paper 1.21-R0.1-SNAPSHOT and Java 21.0.3
[00:31:12 ERROR]: Could not pass event InventoryOpenEvent to Protect v1.1.5
org.mineacademy.protect.lib.exception.FoException: Report: Could not convert item to CompMaterial. Item: ItemStack{FLOW_BANNER_PATTERN x 1}
        at Protect-1.1.5.jar/org.mineacademy.protect.lib.Valid.checkNotNull(Valid.java:60) ~[Protect-1.1.5.jar:?]
        at Protect-1.1.5.jar/org.mineacademy.protect.lib.remain.CompMaterial.fromItem(CompMaterial.java:2480) ~[Protect-1.1.5.jar:?]
        at Protect-1.1.5.jar/org.mineacademy.protect.operator.Rule$RuleCheck.check0(Rule.java:336) ~[Protect-1.1.5.jar:?]
        at Protect-1.1.5.jar/org.mineacademy.protect.operator.Rule$RuleCheck.checkPlayerInventory(Rule.java:240) ~[Protect-1.1.5.jar:?]
        at Protect-1.1.5.jar/org.mineacademy.protect.operator.Rule.filter(Rule.java:181) ~[Protect-1.1.5.jar:?]
        at Protect-1.1.5.jar/org.mineacademy.protect.operator.Rule.filterOpenContainer(Rule.java:135) ~[Protect-1.1.5.jar:?]
        at Protect-1.1.5.jar/org.mineacademy.protect.listener.ScanListener.onInventoryOpen(ScanListener.java:121) ~[Protect-1.1.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor426.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1426) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1702) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.world.level.block.ChestBlock.useWithoutItem(ChestBlock.java:257) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.useWithoutItem(BlockBehaviour.java:1164) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:590) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1871) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

[debug.zip](https://github.com/user-attachments/files/15996963/debug.zip)
[error.log](https://github.com/user-attachments/files/15996964/error.log)

I don't know tbh how to reproduce this error

**Comment by kangarko** [comment]
Thanks, will be solved: https://github.com/kangarko/Foundation/commit/78f69dda22a355b6bec6a90636a1ba64805b7100
